import { DiagramTemplate } from "../types";

// Design Tokens for diagrams that look good in both light and dark modes
const LOGO_BOX_FILL = "rgba(150, 150, 150, 0.07)";
const LOGO_BOX_STROKE = "rgba(150, 150, 150, 0.3)";
const TEXT_MUTED = "rgba(128, 128, 128, 0.8)";
const ARROW_COLOR = "rgba(100, 100, 100, 0.6)";

export const DIAGRAM_CATALOG: DiagramTemplate[] = [
  {
    name: "Secure Web Architecture",
    description:
      "Multi-tier secure web application architecture with Load Balancer, Web Servers, and Database.",
    thumbnail: "Network",
    shapes: {
      rectangles: [
        {
          id: "s-1",
          x: 100,
          y: 100,
          width: 600,
          height: 400,
          strokeDashArray: [5, 5],
          stroke: ARROW_COLOR,
        }, // VPC
        {
          id: "s-2",
          x: 150,
          y: 150,
          width: 500,
          height: 120,
          fill: "rgba(59, 130, 246, 0.08)",
          stroke: "#3b82f6",
        }, // Public Subnet
        {
          id: "s-3",
          x: 150,
          y: 300,
          width: 500,
          height: 150,
          fill: "rgba(16, 185, 129, 0.08)",
          stroke: "#10b981",
        }, // Private Subnet
        {
          id: "s-4",
          x: 350,
          y: 170,
          width: 100,
          height: 60,
          fill: LOGO_BOX_FILL,
          stroke: "#3b82f6",
        }, // Load Balancer
      ],
      images: [
        {
          id: "img-aws-1",
          src: "/logos/aws.svg",
          x: 105,
          y: 105,
          width: 30,
          height: 30,
        },
        {
          id: "img-elb-1",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Networking-Content-Delivery/48/Arch_Elastic-Load-Balancing_48.svg",
          x: 375,
          y: 175,
          width: 50,
          height: 50,
        },
        {
          id: "img-ec2-1",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Compute/48/Arch_Amazon-EC2_48.svg",
          x: 275,
          y: 350,
          width: 50,
          height: 50,
        },
        {
          id: "img-ec2-2",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Compute/48/Arch_Amazon-EC2_48.svg",
          x: 475,
          y: 350,
          width: 50,
          height: 50,
        },
      ],
      circles: [
        {
          id: "c-1",
          x: 300,
          y: 375,
          rx: 40,
          ry: 40,
          fill: LOGO_BOX_FILL,
          stroke: "#10b981",
        }, // App Node 1
        {
          id: "c-2",
          x: 500,
          y: 375,
          rx: 40,
          ry: 40,
          fill: LOGO_BOX_FILL,
          stroke: "#10b981",
        }, // App Node 2
      ],
      texts: [
        {
          id: "t-1",
          x: 110,
          y: 110,
          text: "VPC (AWS Cloud)",
          fontSize: 14,
          width: 150,
          height: 20,
          fontFamily: "Mono",
        },
        {
          id: "t-2",
          x: 160,
          y: 155,
          text: "Public Subnet",
          fontSize: 12,
          width: 100,
          height: 18,
          fontFamily: "Mono",
        },
        {
          id: "t-3",
          x: 160,
          y: 305,
          text: "Private Subnet",
          fontSize: 12,
          width: 100,
          height: 18,
          fontFamily: "Mono",
        },
        {
          id: "t-4",
          x: 365,
          y: 190,
          text: "ELB",
          fontSize: 11,
          width: 70,
          height: 20,
          fontFamily: "Mono",
          textAlign: "center",
        },
        {
          id: "t-5",
          x: 275,
          y: 365,
          text: "API",
          fontSize: 11,
          width: 50,
          height: 20,
          fontFamily: "Mono",
          textAlign: "center",
        },
        {
          id: "t-6",
          x: 475,
          y: 365,
          text: "API",
          fontSize: 11,
          width: 50,
          height: 20,
          fontFamily: "Mono",
          textAlign: "center",
        },
      ],
      connectors: [
        {
          id: "a-1",
          from: { kind: "rect", shapeId: "s-4", anchor: "bottom" },
          to: { kind: "circle", shapeId: "c-1", anchor: "top" },
        },
        {
          id: "a-2",
          from: { kind: "rect", shapeId: "s-4", anchor: "bottom" },
          to: { kind: "circle", shapeId: "c-2", anchor: "top" },
        },
      ],
    },
  },
  {
    name: "Microservices Ecosystem",
    description:
      "Detailed microservices architecture featuring Gateway, Auth, Catalog services and Event Bus.",
    thumbnail: "LayoutGrid",
    shapes: {
      rectangles: [
        {
          id: "m-1",
          x: 50,
          y: 50,
          width: 120,
          height: 250,
          fill: "rgba(249, 115, 22, 0.08)",
          stroke: "#f97316",
        }, // UI / Gateway
        {
          id: "m-2",
          x: 250,
          y: 50,
          width: 150,
          height: 80,
          fill: "rgba(139, 92, 246, 0.08)",
          stroke: "#8b5cf6",
        }, // Auth Service
        {
          id: "m-3",
          x: 250,
          y: 150,
          width: 150,
          height: 80,
          fill: "rgba(236, 72, 153, 0.08)",
          stroke: "#ec4899",
        }, // Catalog Service
        {
          id: "m-4",
          x: 250,
          y: 250,
          width: 150,
          height: 80,
          fill: "rgba(14, 165, 233, 0.08)",
          stroke: "#0ea5e9",
        }, // Order Service
        {
          id: "m-5",
          x: 500,
          y: 50,
          width: 200,
          height: 280,
          strokeDashArray: [4, 4],
          stroke: ARROW_COLOR,
        }, // Event Bus
      ],
      images: [
        {
          id: "img-gw",
          src: "/icons-library/seti-icons/react.svg",
          x: 90,
          y: 70,
          width: 40,
          height: 40,
        },
        {
          id: "img-auth",
          src: "/icons-library/seti-icons/javascript.svg",
          x: 305,
          y: 60,
          width: 30,
          height: 30,
        },
        {
          id: "img-catalog",
          src: "/icons-library/seti-icons/typescript.svg",
          x: 305,
          y: 160,
          width: 30,
          height: 30,
        },
        {
          id: "img-order",
          src: "/icons-library/seti-icons/python.svg",
          x: 305,
          y: 260,
          width: 30,
          height: 30,
        },
        {
          id: "img-k8s",
          src: "/logos/kubernetes.svg",
          x: 580,
          y: 100,
          width: 40,
          height: 40,
        },
      ],
      texts: [
        {
          id: "mt-1",
          x: 60,
          y: 150,
          text: "API Gateway",
          fontSize: 13,
          width: 100,
          height: 20,
          fontFamily: "Clean",
          textAlign: "center",
        },
        {
          id: "mt-2",
          x: 260,
          y: 80,
          text: "Auth Service",
          fontSize: 13,
          width: 130,
          height: 20,
          fontFamily: "Clean",
          textAlign: "center",
        },
        {
          id: "mt-3",
          x: 260,
          y: 180,
          text: "Catalog Service",
          fontSize: 13,
          width: 130,
          height: 20,
          fontFamily: "Clean",
          textAlign: "center",
        },
        {
          id: "mt-4",
          x: 260,
          y: 280,
          text: "Order Service",
          fontSize: 13,
          width: 130,
          height: 20,
          fontFamily: "Clean",
          textAlign: "center",
        },
        {
          id: "mt-5",
          x: 510,
          y: 170,
          text: "Redis Event Bus",
          fontSize: 14,
          width: 180,
          height: 24,
          fontFamily: "Mono",
          textAlign: "center",
        },
      ],
      connectors: [
        {
          id: "ma-1",
          from: { kind: "rect", shapeId: "m-1", anchor: "right" },
          to: { kind: "rect", shapeId: "m-2", anchor: "left" },
        },
        {
          id: "ma-2",
          from: { kind: "rect", shapeId: "m-1", anchor: "right" },
          to: { kind: "rect", shapeId: "m-3", anchor: "left" },
        },
        {
          id: "ma-3",
          from: { kind: "rect", shapeId: "m-1", anchor: "right" },
          to: { kind: "rect", shapeId: "m-4", anchor: "left" },
        },
        {
          id: "ma-4",
          from: { kind: "rect", shapeId: "m-2", anchor: "right" },
          to: { kind: "rect", shapeId: "m-5", anchor: "left" },
        },
        {
          id: "ma-5",
          from: { kind: "rect", shapeId: "m-3", anchor: "right" },
          to: { kind: "rect", shapeId: "m-5", anchor: "left" },
        },
        {
          id: "ma-6",
          from: { kind: "rect", shapeId: "m-4", anchor: "right" },
          to: { kind: "rect", shapeId: "m-5", anchor: "left" },
        },
      ],
    },
  },
  {
    name: "Serverless Edge Stack",
    description:
      "Modern edge-computing stack with Global CDN, Edge Functions and distributed Key-Value store.",
    thumbnail: "Zap",
    shapes: {
      polygons: [
        {
          id: "p-1",
          type: "hexagon",
          x: 100,
          y: 100,
          width: 120,
          height: 120,
          fill: "rgba(234, 179, 8, 0.08)",
          stroke: "#eab308",
        }, // Edge Node 1
        {
          id: "p-2",
          type: "hexagon",
          x: 100,
          y: 250,
          width: 120,
          height: 120,
          fill: "rgba(234, 179, 8, 0.08)",
          stroke: "#eab308",
        }, // Edge Node 2
      ],
      rectangles: [
        {
          id: "r-1",
          x: 350,
          y: 150,
          width: 200,
          height: 100,
          fill: LOGO_BOX_FILL,
          stroke: "#6366f1",
          strokeWidth: 2,
        }, // Global Database
      ],
      texts: [
        {
          id: "et-1",
          x: 110,
          y: 150,
          text: "Edge JS",
          fontSize: 12,
          width: 100,
          height: 18,
          textAlign: "center",
        },
        {
          id: "et-2",
          x: 110,
          y: 300,
          text: "Edge JS",
          fontSize: 12,
          width: 100,
          height: 18,
          textAlign: "center",
        },
        {
          id: "et-3",
          x: 360,
          y: 190,
          text: "Distributed KV",
          fontSize: 14,
          width: 180,
          height: 24,
          textAlign: "center",
          fontFamily: "Mono",
        },
      ],
      connectors: [
        {
          id: "ec-1",
          from: { kind: "poly", shapeId: "p-1", anchor: "right" },
          to: { kind: "rect", shapeId: "r-1", anchor: "left" },
        },
        {
          id: "ec-2",
          from: { kind: "poly", shapeId: "p-2", anchor: "right" },
          to: { kind: "rect", shapeId: "r-1", anchor: "left" },
        },
      ],
    },
  },
  {
    name: "Cloud Data Pipeline",
    description:
      "Multi-cloud data pipeline syncing data between OCI and AWS using EventBridge.",
    thumbnail: "Globe",
    shapes: {
      images: [
        {
          id: "img-1",
          src: "/logos/oci.svg",
          x: 100,
          y: 150,
          width: 60,
          height: 60,
        },
        {
          id: "img-2",
          src: "/logos/aws.svg",
          x: 500,
          y: 150,
          width: 60,
          height: 60,
        },
      ],
      rectangles: [
        {
          id: "r-d1",
          x: 80,
          y: 100,
          width: 100,
          height: 160,
          fill: LOGO_BOX_FILL,
          stroke: LOGO_BOX_STROKE,
        }, // OCI Box
        {
          id: "r-d2",
          x: 480,
          y: 100,
          width: 100,
          height: 160,
          fill: LOGO_BOX_FILL,
          stroke: LOGO_BOX_STROKE,
        }, // AWS Box
        {
          id: "r-d3",
          x: 250,
          y: 140,
          width: 160,
          height: 80,
          fill: "rgba(59, 130, 246, 0.08)",
          stroke: "#3b82f6",
          strokeWidth: 2,
        }, // Link/Sync
      ],
      texts: [
        {
          id: "td-1",
          x: 90,
          y: 110,
          text: "Oracle OCI",
          fontSize: 11,
          width: 80,
          height: 16,
          textAlign: "center",
        },
        {
          id: "td-2",
          x: 490,
          y: 110,
          text: "Amazon AWS",
          fontSize: 11,
          width: 80,
          height: 16,
          textAlign: "center",
        },
        {
          id: "td-3",
          x: 260,
          y: 170,
          text: "Cross-Cloud Sync",
          fontSize: 13,
          width: 140,
          height: 20,
          textAlign: "center",
        },
      ],
      connectors: [
        {
          id: "ad-1",
          from: { kind: "rect", shapeId: "r-d1", anchor: "right" },
          to: { kind: "rect", shapeId: "r-d3", anchor: "left" },
        },
        {
          id: "ad-2",
          from: { kind: "rect", shapeId: "r-d3", anchor: "right" },
          to: { kind: "rect", shapeId: "r-d2", anchor: "left" },
        },
      ],
    },
  },
  {
    name: "Netflix Streaming Architecture",
    description:
      "A comprehensive streaming architecture showing CDN edge, API Gateways, Microservices, and Persistence layers.",
    thumbnail: "Play",
    shapes: {
      rectangles: [
        {
          id: "nf-bg",
          x: 0,
          y: 0,
          width: 900,
          height: 550,
          stroke: "transparent",
          fill: "rgba(255, 0, 0, 0.02)",
        },
        {
          id: "nf-cdn",
          x: 50,
          y: 100,
          width: 150,
          height: 350,
          fill: "rgba(229, 9, 20, 0.05)",
          stroke: "#e50914",
          strokeWidth: 2,
        }, // Open Connect CDN
        {
          id: "nf-aws",
          x: 250,
          y: 50,
          width: 600,
          height: 450,
          strokeDashArray: [8, 8],
          stroke: ARROW_COLOR,
        }, // AWS Cloud
        {
          id: "nf-tier1",
          x: 280,
          y: 150,
          width: 120,
          height: 250,
          fill: LOGO_BOX_FILL,
          stroke: LOGO_BOX_STROKE,
        }, // API Proxy (Zuul)
        {
          id: "nf-tier2",
          x: 450,
          y: 80,
          width: 150,
          height: 380,
          fill: "rgba(100, 100, 100, 0.03)",
          stroke: LOGO_BOX_STROKE,
        }, // Microservices Area
        {
          id: "nf-db-box",
          x: 630,
          y: 80,
          width: 200,
          height: 380,
          stroke: ARROW_COLOR,
          strokeDashArray: [4, 4],
          fill: "rgba(100, 100, 100, 0.02)",
        },
      ],
      images: [
        {
          id: "img-nf-logo",
          src: "/icons-library/seti-icons/react.svg",
          x: 20,
          y: 20,
          width: 40,
          height: 40,
        },
        {
          id: "img-zuul",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Networking-Content-Delivery/48/Arch_Amazon-API-Gateway_48.svg",
          x: 315,
          y: 180,
          width: 50,
          height: 50,
        },
        {
          id: "img-kafka",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Analytics/48/Arch_Amazon-Managed-Streaming-for-Apache-Kafka_48.svg",
          x: 650,
          y: 100,
          width: 50,
          height: 50,
        },
        {
          id: "img-cassandra",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Database/48/Arch_Amazon-Keyspaces_48.svg",
          x: 750,
          y: 250,
          width: 50,
          height: 50,
        },
        {
          id: "img-s3-nf",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Storage/48/Arch_Amazon-Simple-Storage-Service_48.svg",
          x: 750,
          y: 380,
          width: 50,
          height: 50,
        },
      ],
      texts: [
        {
          id: "nf-t1",
          x: 60,
          y: 110,
          text: "Open Connect",
          fontSize: 14,
          width: 130,
          height: 20,
          textAlign: "center",
          fontFamily: "Mono",
        },
        {
          id: "nf-t2",
          x: 60,
          y: 450,
          text: "Global CDN",
          fontSize: 12,
          width: 130,
          height: 18,
          textAlign: "center",
          fill: TEXT_MUTED,
        },
        {
          id: "nf-t3",
          x: 280,
          y: 60,
          text: "AWS Cloud Control Plane",
          fontSize: 14,
          width: 250,
          height: 20,
          fontFamily: "Mono",
        },
        {
          id: "nf-t4",
          x: 290,
          y: 370,
          text: "Zuul Gateway",
          fontSize: 12,
          width: 100,
          height: 18,
          textAlign: "center",
        },
        {
          id: "nf-ms1",
          x: 475,
          y: 120,
          text: "Auth Service",
          fontSize: 11,
          width: 100,
          height: 16,
          textAlign: "center",
        },
        {
          id: "nf-ms2",
          x: 475,
          y: 220,
          text: "Playback DB",
          fontSize: 11,
          width: 100,
          height: 16,
          textAlign: "center",
        },
        {
          id: "nf-ms3",
          x: 475,
          y: 320,
          text: "Personalization",
          fontSize: 11,
          width: 100,
          height: 16,
          textAlign: "center",
        },
        {
          id: "nf-t5",
          x: 730,
          y: 310,
          text: "Cassandra Cluster",
          fontSize: 11,
          width: 100,
          height: 16,
          textAlign: "center",
        },
      ],
      connectors: [
        {
          id: "nf-c1",
          from: { kind: "rect", shapeId: "nf-cdn", anchor: "right" },
          to: { kind: "rect", shapeId: "nf-tier1", anchor: "left" },
        },
        {
          id: "nf-c2",
          from: { kind: "rect", shapeId: "nf-tier1", anchor: "right" },
          to: { kind: "rect", shapeId: "nf-tier2", anchor: "left" },
        },
        {
          id: "nf-c3",
          from: { kind: "rect", shapeId: "nf-tier2", anchor: "right" },
          to: { kind: "rect", shapeId: "nf-db-box", anchor: "left" },
        },
      ],
    },
  },
  {
    name: "Uber Marketplace Architecture",
    description:
      "Highly scalable marketplace architecture for real-time dispatch and supply-demand balancing.",
    thumbnail: "Navigation",
    shapes: {
      rectangles: [
        {
          id: "ub-bg",
          x: 0,
          y: 0,
          width: 900,
          height: 500,
          fill: "rgba(0,0,0,0.02)",
          stroke: "transparent",
        },
        {
          id: "ub-proxy",
          x: 50,
          y: 150,
          width: 100,
          height: 200,
          fill: "rgba(0,0,0,0.05)",
          stroke: "#000000",
        }, // Edge
        {
          id: "ub-core",
          x: 200,
          y: 50,
          width: 450,
          height: 400,
          fill: "rgba(0, 200, 0, 0.02)",
          stroke: "#27ae60",
          strokeWidth: 2,
        }, // Marketplace Core
        {
          id: "ub-dispatch",
          x: 250,
          y: 120,
          width: 150,
          height: 260,
          fill: LOGO_BOX_FILL,
          stroke: LOGO_BOX_STROKE,
        }, // Ringpop Dispatch
        {
          id: "ub-kafka-box",
          x: 450,
          y: 120,
          width: 150,
          height: 260,
          fill: LOGO_BOX_FILL,
          stroke: LOGO_BOX_STROKE,
        }, // Kafka
        {
          id: "ub-db-box",
          x: 700,
          y: 100,
          width: 150,
          height: 300,
          fill: "rgba(52, 152, 219, 0.05)",
          stroke: "#3498db",
          strokeDashArray: [4, 4],
        },
      ],
      images: [
        {
          id: "img-ub-rider",
          src: "/icons-library/seti-icons/react.svg",
          x: 10,
          y: 170,
          width: 30,
          height: 30,
        },
        {
          id: "img-ub-driver",
          src: "/icons-library/seti-icons/javascript.svg",
          x: 10,
          y: 280,
          width: 30,
          height: 30,
        },
        {
          id: "img-ub-kafka",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Analytics/48/Arch_Amazon-Managed-Streaming-for-Apache-Kafka_48.svg",
          x: 495,
          y: 180,
          width: 60,
          height: 60,
        },
        {
          id: "img-ub-mysql",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Database/48/Arch_Amazon-RDS_48.svg",
          x: 750,
          y: 150,
          width: 50,
          height: 50,
        },
      ],
      texts: [
        {
          id: "ub-t1",
          x: 60,
          y: 240,
          text: "Edge Proxy",
          fontSize: 12,
          width: 80,
          height: 18,
          textAlign: "center",
        },
        {
          id: "ub-t2",
          x: 280,
          y: 350,
          text: "Ringpop Dispatch",
          fontSize: 12,
          width: 100,
          height: 18,
          textAlign: "center",
        },
        {
          id: "ub-t3",
          x: 480,
          y: 340,
          text: "Event Streaming",
          fontSize: 11,
          width: 100,
          height: 16,
          textAlign: "center",
        },
        {
          id: "ub-t4",
          x: 730,
          y: 350,
          text: "Schemaless DB",
          fontSize: 11,
          width: 100,
          height: 16,
          textAlign: "center",
        },
        {
          id: "ub-t5",
          x: 220,
          y: 60,
          text: "Marketplace Core Grid",
          fontSize: 14,
          width: 200,
          height: 20,
          fontFamily: "Mono",
        },
      ],
      connectors: [
        {
          id: "ub-c1",
          from: { kind: "rect", shapeId: "ub-proxy", anchor: "right" },
          to: { kind: "rect", shapeId: "ub-dispatch", anchor: "left" },
        },
        {
          id: "ub-c2",
          from: { kind: "rect", shapeId: "ub-dispatch", anchor: "right" },
          to: { kind: "rect", shapeId: "ub-kafka-box", anchor: "left" },
        },
        {
          id: "ub-c3",
          from: { kind: "rect", shapeId: "ub-kafka-box", anchor: "right" },
          to: { kind: "rect", shapeId: "ub-db-box", anchor: "left" },
        },
      ],
    },
  },
  {
    name: "Real-time Messaging Architecture",
    description:
      "Modern chat architecture optimized for latency and high concurrency (WhatsApp/Discord style).",
    thumbnail: "MessageSquare",
    shapes: {
      rectangles: [
        {
          id: "ch-client-area",
          x: 50,
          y: 50,
          width: 120,
          height: 480,
          fill: "rgba(100, 100, 100, 0.05)",
          stroke: LOGO_BOX_STROKE,
        },
        {
          id: "ch-gateway",
          x: 250,
          y: 100,
          width: 150,
          height: 380,
          fill: "rgba(16, 185, 129, 0.05)",
          stroke: "#10b981",
          strokeWidth: 2,
        }, // Websocket Gateway
        {
          id: "ch-services",
          x: 500,
          y: 50,
          width: 200,
          height: 480,
          fill: LOGO_BOX_FILL,
          stroke: LOGO_BOX_STROKE,
        }, // Backend Services
        {
          id: "ch-db-area",
          x: 780,
          y: 100,
          width: 120,
          height: 380,
          fill: "rgba(99, 102, 241, 0.05)",
          stroke: "#6366f1",
          strokeDashArray: [4, 4],
        }, // Persistent Storage
      ],
      images: [
        {
          id: "img-ch-ws",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_App-Integration/48/Arch_AWS-AppSync_48.svg",
          x: 300,
          y: 200,
          width: 50,
          height: 50,
        },
        {
          id: "img-ch-redis",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Database/48/Arch_Amazon-ElastiCache_48.svg",
          x: 575,
          y: 120,
          width: 50,
          height: 50,
        },
        {
          id: "img-ch-dynamo",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Database/48/Arch_Amazon-DynamoDB_48.svg",
          x: 815,
          y: 220,
          width: 50,
          height: 50,
        },
      ],
      texts: [
        {
          id: "ch-t1",
          x: 60,
          y: 240,
          text: "Mobile Clients",
          fontSize: 12,
          width: 100,
          height: 20,
          textAlign: "center",
        },
        {
          id: "ch-t2",
          x: 275,
          y: 400,
          text: "Websocket Gateway",
          fontSize: 12,
          width: 100,
          height: 20,
          textAlign: "center",
        },
        {
          id: "ch-t3",
          x: 550,
          y: 80,
          text: "Chat Microservices",
          fontSize: 12,
          width: 100,
          height: 20,
          textAlign: "center",
        },
        {
          id: "ch-t4",
          x: 790,
          y: 400,
          text: "Message Store",
          fontSize: 12,
          width: 100,
          height: 20,
          textAlign: "center",
        },
        {
          id: "ch-ms1",
          x: 520,
          y: 200,
          text: "Presence",
          fontSize: 11,
          width: 150,
          height: 16,
          textAlign: "center",
        },
        {
          id: "ch-ms2",
          x: 520,
          y: 280,
          text: "User Service",
          fontSize: 11,
          width: 150,
          height: 16,
          textAlign: "center",
        },
        {
          id: "ch-ms3",
          x: 520,
          y: 360,
          text: "Push Notif",
          fontSize: 11,
          width: 150,
          height: 16,
          textAlign: "center",
        },
      ],
      connectors: [
        {
          id: "ch-c1",
          from: { kind: "rect", shapeId: "ch-client-area", anchor: "right" },
          to: { kind: "rect", shapeId: "ch-gateway", anchor: "left" },
        },
        {
          id: "ch-c2",
          from: { kind: "rect", shapeId: "ch-gateway", anchor: "right" },
          to: { kind: "rect", shapeId: "ch-services", anchor: "left" },
        },
        {
          id: "ch-c3",
          from: { kind: "rect", shapeId: "ch-services", anchor: "right" },
          to: { kind: "rect", shapeId: "ch-db-area", anchor: "left" },
        },
      ],
    },
  },
  {
    name: "AI/ML Production Pipeline",
    description:
      "End-to-end machine learning workflow from data ingestion to model inference.",
    thumbnail: "Brain",
    shapes: {
      rectangles: [
        {
          id: "ai-lake",
          x: 50,
          y: 100,
          width: 140,
          height: 300,
          fill: "rgba(59, 130, 246, 0.05)",
          stroke: "#3b82f6",
          strokeDashArray: [4, 4],
        }, // Data Lake
        {
          id: "ai-training",
          x: 250,
          y: 50,
          width: 400,
          height: 180,
          fill: "rgba(139, 92, 246, 0.05)",
          stroke: "#8b5cf6",
          strokeDashArray: [5, 5],
        }, // Training Cluster
        {
          id: "ai-inference",
          x: 250,
          y: 280,
          width: 400,
          height: 180,
          fill: "rgba(16, 185, 129, 0.05)",
          stroke: "#10b981",
        }, // Serving Cluster
        {
          id: "ai-api",
          x: 720,
          y: 100,
          width: 120,
          height: 300,
          fill: LOGO_BOX_FILL,
          stroke: LOGO_BOX_STROKE,
        }, // API Consumption
      ],
      images: [
        {
          id: "img-ai-s3",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Storage/48/Arch_Amazon-Simple-Storage-Service_48.svg",
          x: 95,
          y: 200,
          width: 50,
          height: 50,
        },
        {
          id: "img-ai-sm",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Artificial-Intelligence/48/Arch_Amazon-SageMaker-AI_48.svg",
          x: 425,
          y: 100,
          width: 60,
          height: 60,
        },
        {
          id: "img-ai-bedrock",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Artificial-Intelligence/48/Arch_Amazon-Bedrock_48.svg",
          x: 425,
          y: 330,
          width: 60,
          height: 60,
        },
        {
          id: "img-ai-gate",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Networking-Content-Delivery/48/Arch_Amazon-API-Gateway_48.svg",
          x: 755,
          y: 200,
          width: 50,
          height: 50,
        },
      ],
      texts: [
        {
          id: "ai-t1",
          x: 60,
          y: 120,
          text: "Data Lake (S3)",
          fontSize: 12,
          width: 120,
          height: 20,
          textAlign: "center",
        },
        {
          id: "ai-t2",
          x: 270,
          y: 60,
          text: "SageMaker Training Environment",
          fontSize: 13,
          width: 360,
          height: 20,
          textAlign: "center",
          fontFamily: "Mono",
        },
        {
          id: "ai-t3",
          x: 270,
          y: 290,
          text: "Inference Layer (Bedrock)",
          fontSize: 13,
          width: 360,
          height: 20,
          textAlign: "center",
          fontFamily: "Mono",
        },
        {
          id: "ai-t4",
          x: 730,
          y: 120,
          text: "API Endpoints",
          fontSize: 12,
          width: 100,
          height: 20,
          textAlign: "center",
        },
      ],
      connectors: [
        {
          id: "ai-c1",
          from: { kind: "rect", shapeId: "ai-lake", anchor: "right" },
          to: { kind: "rect", shapeId: "ai-training", anchor: "left" },
        },
        {
          id: "ai-c2",
          from: { kind: "rect", shapeId: "ai-training", anchor: "bottom" },
          to: { kind: "rect", shapeId: "ai-inference", anchor: "top" },
        },
        {
          id: "ai-c3",
          from: { kind: "rect", shapeId: "ai-inference", anchor: "right" },
          to: { kind: "rect", shapeId: "ai-api", anchor: "left" },
        },
      ],
    },
  },
  {
    name: "Kubernetes Service Mesh",
    description:
      "Highly available Kubernetes cluster with Control Plane, Worker Nodes and Istio Mesh.",
    thumbnail: "Box",
    shapes: {
      rectangles: [
        {
          id: "k8-boundary",
          x: 0,
          y: 0,
          width: 900,
          height: 500,
          fill: "rgba(50, 100, 255, 0.02)",
          stroke: "#3366cc",
          strokeWidth: 2,
        }, // Cluster
        {
          id: "k8-master",
          x: 50,
          y: 50,
          width: 200,
          height: 400,
          fill: LOGO_BOX_FILL,
          stroke: "#3366cc",
        }, // Control Plane
        {
          id: "k8-worker-1",
          x: 350,
          y: 50,
          width: 220,
          height: 180,
          fill: "rgba(0, 0, 0, 0.03)",
          stroke: LOGO_BOX_STROKE,
        }, // Node 1
        {
          id: "k8-worker-2",
          x: 350,
          y: 270,
          width: 220,
          height: 180,
          fill: "rgba(0, 0, 0, 0.03)",
          stroke: LOGO_BOX_STROKE,
        }, // Node 2
        {
          id: "k8-lb",
          x: 700,
          y: 150,
          width: 120,
          height: 200,
          fill: "rgba(16, 185, 129, 0.05)",
          stroke: "#10b981",
        }, // Load Balancer
      ],
      images: [
        {
          id: "img-k8-logo",
          src: "/logos/kubernetes.svg",
          x: 125,
          y: 150,
          width: 50,
          height: 50,
        },
        {
          id: "img-k8-eks",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Containers/48/Arch_Amazon-Elastic-Kubernetes-Service_48.svg",
          x: 125,
          y: 250,
          width: 50,
          height: 50,
        },
        {
          id: "img-k8-node1",
          src: "/icons-library/seti-icons/react.svg",
          x: 435,
          y: 100,
          width: 50,
          height: 50,
        },
        {
          id: "img-k8-node2",
          src: "/icons-library/seti-icons/typescript.svg",
          x: 435,
          y: 320,
          width: 50,
          height: 50,
        },
      ],
      texts: [
        {
          id: "k8-t1",
          x: 60,
          y: 70,
          text: "Control Plane",
          fontSize: 14,
          width: 180,
          height: 24,
          textAlign: "center",
          fontFamily: "Mono",
        },
        {
          id: "k8-t2",
          x: 360,
          y: 60,
          text: "Worker Node 1",
          fontSize: 12,
          width: 200,
          height: 20,
          textAlign: "center",
        },
        {
          id: "k8-t3",
          x: 360,
          y: 280,
          text: "Worker Node 2",
          fontSize: 12,
          width: 200,
          height: 20,
          textAlign: "center",
        },
        {
          id: "k8-t4",
          x: 710,
          y: 170,
          text: "Ingress Controller",
          fontSize: 12,
          width: 100,
          height: 20,
          textAlign: "center",
        },
      ],
      connectors: [
        {
          id: "k8-c1",
          from: { kind: "rect", shapeId: "k8-master", anchor: "right" },
          to: { kind: "rect", shapeId: "k8-worker-1", anchor: "left" },
        },
        {
          id: "k8-c2",
          from: { kind: "rect", shapeId: "k8-master", anchor: "right" },
          to: { kind: "rect", shapeId: "k8-worker-2", anchor: "left" },
        },
        {
          id: "k8-c3",
          from: { kind: "rect", shapeId: "k8-lb", anchor: "left" },
          to: { kind: "rect", shapeId: "k8-worker-1", anchor: "right" },
        },
        {
          id: "k8-c4",
          from: { kind: "rect", shapeId: "k8-lb", anchor: "left" },
          to: { kind: "rect", shapeId: "k8-worker-2", anchor: "right" },
        },
      ],
    },
  },
  {
    name: "Serverless Web Full-Stack",
    description:
      "Fully managed serverless architecture for web apps with Auth, API, and NoSQL Database.",
    thumbnail: "Cpu",
    shapes: {
      rectangles: [
        {
          id: "sv-frontend",
          x: 50,
          y: 50,
          width: 150,
          height: 400,
          fill: "rgba(249, 115, 22, 0.05)",
          stroke: "#f97316",
        }, // Frontend Area
        {
          id: "sv-security",
          x: 250,
          y: 150,
          width: 120,
          height: 200,
          fill: "rgba(229, 231, 235, 0.1)",
          stroke: LOGO_BOX_STROKE,
          strokeDashArray: [4, 4],
        }, // Auth
        {
          id: "sv-logic",
          x: 450,
          y: 50,
          width: 180,
          height: 400,
          fill: "rgba(139, 92, 246, 0.05)",
          stroke: "#8b5cf6",
          strokeWidth: 2,
        }, // API & Lambda
        {
          id: "sv-data",
          x: 700,
          y: 100,
          width: 150,
          height: 300,
          fill: "rgba(59, 130, 246, 0.05)",
          stroke: "#3b82f6",
          strokeDashArray: [4, 4],
        }, // DynamoDB
      ],
      images: [
        {
          id: "img-sv-s3",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Storage/48/Arch_Amazon-Simple-Storage-Service_48.svg",
          x: 100,
          y: 150,
          width: 50,
          height: 50,
        },
        {
          id: "img-sv-cf",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Networking-Content-Delivery/48/Arch_Amazon-CloudFront_48.svg",
          x: 100,
          y: 250,
          width: 50,
          height: 50,
        },
        {
          id: "img-sv-cog",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Security-Identity-Compliance/48/Arch_Amazon-Cognito_48.svg",
          x: 285,
          y: 200,
          width: 50,
          height: 50,
        },
        {
          id: "img-sv-api",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Networking-Content-Delivery/48/Arch_Amazon-API-Gateway_48.svg",
          x: 515,
          y: 150,
          width: 50,
          height: 50,
        },
        {
          id: "img-sv-lam",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Compute/48/Arch_AWS-Lambda_48.svg",
          x: 515,
          y: 250,
          width: 50,
          height: 50,
        },
        {
          id: "img-sv-db",
          src: "/icons-library/aws-icons/Architecture-Service-Icons_07312025/Arch_Database/48/Arch_Amazon-DynamoDB_48.svg",
          x: 750,
          y: 220,
          width: 50,
          height: 50,
        },
      ],
      texts: [
        {
          id: "sv-t1",
          x: 60,
          y: 70,
          text: "Static Web Hosting",
          fontSize: 12,
          width: 130,
          height: 20,
          textAlign: "center",
        },
        {
          id: "sv-t2",
          x: 260,
          y: 360,
          text: "Identity (Cognito)",
          fontSize: 11,
          width: 100,
          height: 20,
          textAlign: "center",
        },
        {
          id: "sv-t3",
          x: 460,
          y: 70,
          text: "Serverless Compute",
          fontSize: 13,
          width: 160,
          height: 24,
          textAlign: "center",
          fontFamily: "Mono",
        },
        {
          id: "sv-t4",
          x: 710,
          y: 120,
          text: "Global Message Store",
          fontSize: 12,
          width: 130,
          height: 20,
          textAlign: "center",
        },
      ],
      connectors: [
        {
          id: "sv-c1",
          from: { kind: "rect", shapeId: "sv-frontend", anchor: "right" },
          to: { kind: "rect", shapeId: "sv-logic", anchor: "left" },
        },
        {
          id: "sv-c2",
          from: { kind: "rect", shapeId: "sv-logic", anchor: "right" },
          to: { kind: "rect", shapeId: "sv-data", anchor: "left" },
        },
        {
          id: "sv-c3",
          from: { kind: "rect", shapeId: "sv-frontend", anchor: "bottom" },
          to: { kind: "rect", shapeId: "sv-security", anchor: "left" },
        },
        {
          id: "sv-c4",
          from: { kind: "rect", shapeId: "sv-security", anchor: "right" },
          to: { kind: "rect", shapeId: "sv-logic", anchor: "left" },
        },
      ],
    },
  },
];
