/**
 * @file generateText.ts
 * @description Provides a utility to generate plain text or tool-based responses
 * from the GLM-4.7-Flash model. This is used for general chat, summaries,
 * and logic that doesn't require a strict JSON schema.
 */

import { CLOUDFLARE_API_KEY, GLM_WORKER_URL } from "@/lib/env";

/**
 * Message Interface
 * Defines the structure for conversation history, including support for
 * advanced roles like 'tool' or 'developer'.
 */
export interface Message {
  role: "system" | "user" | "assistant" | "tool" | "developer";
  content: string | unknown[]; // Can be a string or a complex content array
  name?: string; // Optional identifier for the sender
  tool_calls?: unknown[]; // List of tool calls generated by the assistant
  tool_call_id?: string; // ID linking a 'tool' role message back to a call
}

/**
 * GenerateTextOptions Interface
 * Configures the sampling and behavior of the text generation request.
 */
export interface GenerateTextOptions {
  messages: Message[];
  temperature?: number; // Controls randomness (0 = deterministic, 1 = creative)
  top_p?: number; // Nucleus sampling threshold
  max_tokens?: number; // Limit on the length of the generated response
  stream?: boolean; // Whether to stream the response (currently handled as boolean)
  stop?: string[]; // Sequences where the model should stop generating
  tools?: unknown[]; // Definitions of tools the model can call
  tool_choice?: "none" | "auto" | "required"; // Instructions on tool usage
}

/**
 * generateText
 *
 * Sends a request to the GLM-4.7-Flash worker to generate a textual response.
 *
 * @param options - The full set of messages and parameters for the request.
 * @returns A Promise resolving to the text content of the AI's response.
 */
export const generateText = async (
  options: GenerateTextOptions
): Promise<string> => {
  // --- 1. Security & Environment Checks ---
  if (!GLM_WORKER_URL) {
    throw new Error("GLM_WORKER_URL is not set in environment variables");
  }

  if (!CLOUDFLARE_API_KEY) {
    throw new Error("CLOUDFLARE_API_KEY is not set in environment variables");
  }

  // --- 2. Endpoint Setup ---
  const url = GLM_WORKER_URL;
  const headers = {
    "Content-Type": "application/json",
    Authorization: `Bearer ${CLOUDFLARE_API_KEY}`,
  };

  // --- 3. API Execution ---
  // Defaulting stream to false if not provided.
  const response = await fetch(url, {
    method: "POST",
    headers: headers,
    body: JSON.stringify({
      ...options,
      stream: options.stream ?? false,
    }),
  });

  // --- 4. Error Handling ---
  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(
      `GLM-4.7-Flash Worker Error (${response.status}): ${errorText}`
    );
  }

  // --- 5. Data Extraction ---
  const result = await response.json();

  // Validate the presence of the expected response fields.
  if (!result.choices || !result.choices[0] || !result.choices[0].message) {
    throw new Error("Unexpected response format from GLM-4.7-Flash Worker");
  }

  // Return the raw text content from the first response choice.
  return result.choices[0].message.content;
};
